---
title: "Merging metadata"
author: "Leonardo Collado-Torres and Ashkaun Razmara"
date: "10/3/2017"
output: html_document
---

## Setup

```{r}
library('devtools')
```


## Read tables

```{r}
## Find table files and name them by project id
table_files <- dir('../SRA_metadata', pattern = '.csv$', full.names = TRUE)
names(table_files) <- sapply(strsplit(table_files, ', '), function(x) { strsplit(x[2], '-Table')[[1]][1] })

## Read the table files
table_content <- lapply(table_files, read.csv, header = TRUE, stringsAsFactors = FALSE)

## Drop empty columns (they start with X)
table_content <- lapply(table_content, function(tab) {
  idx <- grep('^X', colnames(tab))
#  colnames(tab)[idx]
#  summary(is.na(tab[, idx]))
  if(length(idx) > 0) {
    return(tab[, -idx])
  } else {
    return(tab)
  }
  
})


table_cols <- do.call(rbind, lapply(seq_len(length(table_content)), function(i) {
  tab <- table_content[[i]]
  df <- data.frame(columns = colnames(tab), number_na = sapply(tab, function(var) { sum(is.na(var))}), n = nrow(tab), study = names(table_content)[i], stringsAsFactors = FALSE)
  df$percent_na <- df$number_na / df$n * 100
  df$number_obs <- df$n - df$number_na
  df$percent_obs <- 100 - df$percent_na
  rownames(df) <- NULL
  return(df)
}))

dim(table_cols)
summary(table_cols)

sort(table(table_cols$columns), decreasing = TRUE)

#boxplot(percent_na ~ columns, data = table_cols, las = 2)
hist(subset(table_cols, columns == 'Age')$percent_na)
summary(subset(table_cols, columns == 'Age')$percent_na)

summary(subset(table_cols, columns == 'Age')$percent_na[subset(table_cols, columns == 'Age')$percent_na != 100])
table(subset(table_cols, columns == 'Age')$percent_na[subset(table_cols, columns == 'Age')$percent_na != 100])
```


## Merging tables


```{r}
## Get the unique columns
unique_cols <- unique(table_cols$columns)
## Don't sort, as requested by Ashkaun
#unique_cols_sorted <- sort(tolower(unique_cols))
unique_cols_sorted <- tolower(unique_cols)

## Build a new set of tables by study with all the columns
table_new <- lapply(table_content, function(tab) {
  missing_cols <- unique_cols[!unique_cols %in% colnames(tab)]
  if(length(missing_cols) > 0) {
    df_add <- as.data.frame(matrix(NA, nrow = nrow(tab), ncol = length(missing_cols)))
    colnames(df_add) <- missing_cols
    df_new <- cbind(tab, df_add)
    colnames(df_new) <- tolower(colnames(df_new))
    res <- df_new[, match(unique_cols_sorted, colnames(df_new))]
  } else {
    res <- tab
  }
  return(res)
})

recount_brain <- do.call(rbind, table_new)
```

## Merge with recount

```{r}
## Check which samples are in recount
library(recount)
m <- all_metadata('sra')

map <- match(m$run, recount_brain$run_s)
table(!is.na(map))

map_r <- match(recount_brain$run_s, m$run)
table(!is.na(map_r))

## Add whether the sample is present in recount
recount_brain$present_in_recount <- !is.na(map_r)

## Sort alphabeitcally and change dots for underscores
#recount_brain <- recount_brain[, sort(colnames(recount_brain))]
colnames(recount_brain) <- gsub('\\.', '_', colnames(recount_brain))

## Fix some issues
recount_brain$sex <- tolower(recount_brain$sex)

missing_na <- sort(sapply(recount_brain, function(x) {
    sum(x == '', na.rm = TRUE)
}))
missing_na[missing_na > 0]

subset(recount_brain, sex == '')

for(i in seq_len(ncol(recount_brain))) {
    if(sum(recount_brain[, i] == '', na.rm = TRUE) > 0) {
        recount_brain[which(recount_brain[, i] == ''), i] <- NA
    }
}

## Save the data
save(recount_brain, file = 'recount_brain.Rdata')
write.csv(recount_brain, file = 'recount_brain.csv', quote = TRUE, row.names = FALSE)

## Explore why some samples are missing in recount but present in recount_brain
table(recount_brain$organism_s[ is.na(map_r) ], useNA = 'ifany')
table(recount_brain$organism_s[ is.na(map_r) ], recount_brain$platform_s[ is.na(map_r) ], useNA = 'ifany')
table(recount_brain$sra_study_s[ is.na(map_r) ], recount_brain$platform_s[ is.na(map_r) ], useNA = 'ifany')

table(recount_brain$assay_type_s, recount_brain$assay_type, useNA = 'ifany')
table(recount_brain$assay_type_s[ is.na(map_r) ], useNA = 'ifany')
```

## Explore a bit

```{r}
table(recount_brain$disease, useNA = 'ifany')
table(recount_brain$age_units, useNA = 'ifany')

#subset(recount_brain, age_units == 'Child')


##
boxplot(age ~ age_units, data = recount_brain)
boxplot(age ~ age_units, data = recount_brain[recount_brain$present_in_recount, ])

table(recount_brain$pmi_units, recount_brain$present_in_recount, useNA = 'ifany')
table(!is.na(recount_brain$pmi))
boxplot(recount_brain$pmi, ylab = 'PMI (hours)')
plot(age ~ pmi, data = recount_brain[recount_brain$present_in_recount & recount_brain$age_units == 'Years', ], ylab = 'Age (years)')

boxplot(age ~ sex, data = recount_brain[recount_brain$present_in_recount & recount_brain$age_units == 'Years', ], ylab = 'Age (years)')

boxplot(age ~ disease_status, data = recount_brain[recount_brain$present_in_recount & recount_brain$age_units == 'Years', ], ylab = 'Age (years)')
boxplot(age ~ disease_status + sex, data = recount_brain[recount_brain$present_in_recount & recount_brain$age_units == 'Years', ], ylab = 'Age (years)')

table(recount_brain$development, recount_brain$present_in_recount, useNA = 'ifany')

subset(recount_brain, development == 'Months')
## Study SRP045638 could have a problem

par(mar = c(18, 4, 4, 2) + 0.1)
boxplot(age ~ disease, data = recount_brain[recount_brain$present_in_recount & recount_brain$age_units == 'Years', ], las = 2, ylab = 'Age (years)')
```



## Reproducibility

```{r}
## Reproducibility info
proc.time()
message(Sys.time())
options(width = 120)
session_info()
```

