shinyUI(navbarPage(title = 'explore recount-brain interactively',
    tabPanel('Explore data',
        sidebarLayout(
            sidebarPanel(
                downloadButton('downloadData', 'Download table'),
                helpText('Useful in case you subsetted your data'),
                width = 2
            ),
            mainPanel(
                tabsetPanel(
                    tabPanel('Raw Data', DT::dataTableOutput('raw_data')),
                    tabPanel('Raw summary',
                        downloadLink('download_summary',
                            'Download raw summary'),
                        verbatimTextOutput('raw_summary')
                    ),
                    tabPanel('One variable',
                        uiOutput('summary'),
                        plotOutput('summary_plot'),
                        uiOutput('summary_info'),
                        hr(),
                        p('Code for reproducing the figure:'),
                        verbatimTextOutput('plot_code_one')
                    ),
                    tabPanel('Two variables',
                        uiOutput('summary_two_x'),
                        uiOutput('summary_two_y'),
                        helpText('Sometimes the plot will look better if you swap the X and Y axis variables.'),
                        actionButton('goTwo', 'Make two-way plot'),
                        helpText('If your data set is large, this might take a while. Please be patient!'),
                        plotOutput('summary_plot_two'),
                        verbatimTextOutput('summary_table_two'),
                        hr(),
                        p('Code for reproducing the figure:'),
                        verbatimTextOutput('plot_code_two')
                    ),
                    tabPanel('Plot colors',
                        p('Select a palette and a color number from the options showed below'),
                        selectInput('palette', 'Color palette',
                            choices = rownames(RColorBrewer::brewer.pal.info),
                            selected = 'Set1'),
                        sliderInput('colorn', 'Color number', value = 2,
                            min = 1, max = 9, step = 1, round = TRUE,
                            ticks = FALSE),
                        plotOutput('colors'),
                        tags$br(),
                        tags$br(),
                        tags$br(),
                        tags$br(),
                        tags$br(),
                        tags$br(),
                        tags$br(),
                        tags$br(),
                        tags$br(),
                        tags$br(),
                        tags$br(),
                        tags$br(),
                        tags$br(),
                        tags$br(),
                        tags$br(),
                        tags$br(),
                        tags$br(),
                        tags$br()
                    ),
                    tabPanel('Documentation',
                        hr(),
                        p('All columns of the ', strong('raw data'), ' table are sortable and searchable. Subsetting on the raw data will affect summary statistics and plots in the other tabs.'),
                        hr(),
                        p('The recount-brain shiny application is a specific case of the ', HTML('<a href="https://jhubiostatistics.shinyapps.io/shinycsv/">shinycsv</a>'), ' application that can display many different types of tables. For example, shinycsv can display a table in the first sheet of a Excel file, a csv file you upload, etc. In this case, we are displaying the ', HTML('<a href="https://github.com/LieberInstitute/recount-brain/blob/master/cross_studies_metadata/recount_brain_v2.csv">recount_brain_v2.csv</a>'), 'file.'), 
                        p('The two-way summary plots can take some time to compute if you have a large data set, that is why you have to click on the ', strong('make two-way plot'), ' button to create the plot and update the summary table.'),
                        hr(),
                        HTML('View this app in a new window at <a href ="https://jhubiostatistics.shinyapps.io/recount-brain/">jhubiostatistics.shinyapps.io/recount-brain/</a>.')
                    ),
                    hr(),
                    p('This shiny application was developed by the data science team at the Lieber Institute for Brain Development and is deployed on the Department of Biostatistics at Johns Hopkins Bloomberg School of Public Health shinyapps account.'),
                    hr(),
                    p(HTML('<a href="http://www.libd.org/"><img src="http://aejaffe.com/media/LIBD_logo.jpg" align="left" width="250px"/></a>')),
                    p(HTML('<a href="http://www.jhsph.edu/departments/biostatistics/"><img src="http://aejaffe.com/media/jhu-bloomberg-logo.jpg" align="right" width="250px"/></a>')),
                    p(HTML('<a href="http://lieberinstitute.github.io/recount-brain/"><img src="https://raw.githubusercontent.com/LieberInstitute/recount-brain/master/recount_brain.png" align="right" width="250px"/></a>')),
                    tags$br(),
                    tags$br(),
                    tags$br(),
                    tags$br(),
                    tags$br(),
                    tags$br(),
                    tags$br(),
                    tags$br(),
                    tags$br(),
                    tags$br()
                )
            )
        )
    ),
    tabPanel('Help or feedback',
        p('Please get in touch with the recount-brain team via ', HTML('<a href="https://github.com/LieberInstitute/recount-brain/issues">LieberInstitute/recount-brain</a>.')),
        hr(),
        p('The following information will be useful to them:'),
        verbatimTextOutput('session_info'),
        p('Also try to include a small reproducible example so they can figure out what went wrong. Thank you!'),
        hr(),
        p('This shiny application was developed by the data science team at the Lieber Institute for Brain Development and is deployed on the Department of Biostatistics at Johns Hopkins Bloomberg School of Public Health shinyapps account.'),
        hr(),
        p(HTML('<a href="http://www.libd.org/"><img src="http://aejaffe.com/media/LIBD_logo.jpg" align="left" width="250px"/></a>')),
        p(HTML('<a href="http://www.jhsph.edu/departments/biostatistics/"><img src="http://aejaffe.com/media/jhu-bloomberg-logo.jpg" align="right" width="250px"/></a>')),
         p(HTML('<a href="http://lieberinstitute.github.io/recount-brain/"><img src="https://raw.githubusercontent.com/LieberInstitute/recount-brain/master/recount_brain.png" align="right" width="250px"/></a>')),
        tags$br(),
        tags$br(),
        tags$br(),
        tags$br(),
        tags$br(),
        tags$br(),
        tags$br(),
        tags$br(),
        tags$br(),
        tags$br()
    )
))


